src/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from src.task_manager.views import HomeView
from src.task_manager.users.views import CustomLoginView, custom_logout
from .views import trigger_error

handler404 = 'task_manager.views.handler404'
handler500 = 'task_manager.views.handler500'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('task_manager.users.urls')),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', custom_logout, name='logout'),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('error-test/', trigger_error, name='error-test'),
]

task_manager/tasks/urls.py
from django.urls import path
from . import views
from django.contrib.auth import get_user_model
from django.shortcuts import redirect


def check_users_exist(request):
    if not get_user_model().objects.exists():
        return redirect('tasks:list')
    return None


app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='list'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from task_manager.views import HomeView
from task_manager.users.views import CustomLoginView, custom_logout
from .views import trigger_error

handler404 = 'task_manager.views.handler404'
handler500 = 'task_manager.views.handler500'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('task_manager.users.urls')),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', custom_logout, name='logout'),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('error-test/', trigger_error, name='error-test'),
]

task_manager/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.UserListView.as_view(), name='users'),
    path('create/', views.UserCreateView.as_view(), name='register'),
    path(
        '<int:pk>/update/',
        views.UserUpdateView.as_view(),
        name='user_update'
    ),
    path('<int:pk>/delete/',
         views.UserDeleteView.as_view(),
         name='user_delete'
         ),
]

task_manager/labels/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Label


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = ['name']
        labels = {
            'name': _('Имя'),
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }

task_manager/statuses/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import Status


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name']
        labels = {
            'name': _('Имя'),
        }
        widgets = {
            'имя': forms.TextInput(attrs={'class': 'form-control'}),
        }

tasks/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from .models import Task
from statuses.models import Status
from labels.models import Label

User = get_user_model()


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'executor', 'labels']
        labels = {
            'name': _('Имя'),
            'description': _('Содержание'),
            'status': _('Статус'),
            'executor': _('Исполнитель'),
            'labels': _('Метка'),
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'status': forms.Select(attrs={'class': 'form-select'}),
            'executor': forms.Select(attrs={'class': 'form-select'}),
            'labels': forms.SelectMultiple(attrs={'class': 'form-select'}),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        self.fields['status'].queryset = Status.objects.all()
        self.fields['executor'].queryset = User.objects.all()
        # Теперь Label определен, поэтому эта строка будет работать
        self.fields['labels'].queryset = Label.objects.all()
        self.fields['labels'].label = _('Метка')

task_manager/labels/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import ProtectedError
from django.shortcuts import redirect
from .models import Label
from .forms import LabelForm
from task_manager.tasks.models import Task


class LabelListView(LoginRequiredMixin, ListView):
    model = Label
    template_name = 'labels/list.html'
    context_object_name = 'labels'


class LabelCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/form.html'
    success_url = reverse_lazy('labels:list')
    success_message = _('Метка успешно создана')


class LabelUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/form.html'
    success_url = reverse_lazy('labels:list')
    success_message = _('Метка успешно изменена')


class LabelDeleteView(LoginRequiredMixin, DeleteView):
    model = Label
    template_name = 'labels/delete.html'
    success_url = reverse_lazy('labels:list')
    success_message = _('Метка успешно удалена')
    error_message = _('Невозможно удалить метку, потому что она используется')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request,
                _('Вы не авторизованы! Пожалуйста, войдите в систему.')
            )
            return redirect(reverse_lazy('login'))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if Task.objects.filter(labels=self.object).exists():
            messages.error(request, self.error_message)
            return redirect(self.success_url)

        try:
            response = super().post(request, *args, **kwargs)
            messages.success(request, self.success_message)
            return response
        except ProtectedError:
            messages.error(request, self.error_message)
            return redirect(self.success_url)

task_manager/statuses/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import ProtectedError
from django.shortcuts import redirect
from .models import Status
from .forms import StatusForm
from task_manager.tasks.models import Task


class StatusListView(LoginRequiredMixin, ListView):
    model = Status
    template_name = 'statuses/list.html'
    context_object_name = 'statuses'


class StatusCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = 'statuses/form.html'
    success_url = reverse_lazy('statuses:list')
    success_message = _('Статус успешно создан')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Создать статус')
        return context


class StatusUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Status
    form_class = StatusForm
    template_name = 'statuses/form.html'
    success_url = reverse_lazy('statuses:list')
    success_message = _('Статус успешно изменен')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Изменить статус')
        return context


class StatusDeleteView(LoginRequiredMixin, DeleteView):
    model = Status
    template_name = 'statuses/delete.html'
    success_url = reverse_lazy('statuses:list')
    success_message = _('Статус успешно удален')
    error_message = _('Невозможно удалить статус, потому что он используется')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request,
                _('Вы не авторизованы! Пожалуйста, войдите в систему.')
            )
            return redirect(reverse_lazy('login'))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()

        if Task.objects.filter(status=self.object).exists():
            messages.error(request, self.error_message)
            return redirect(self.success_url)

        try:
            response = super().post(request, *args, **kwargs)
            messages.success(request, self.success_message)
            return response
        except ProtectedError:
            messages.error(request, self.error_message)
            return redirect(self.success_url)

task_manager/tasks/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from django.shortcuts import redirect
from .models import Task
from .forms import TaskForm
from django_filters.views import FilterView
from .filters import TaskFilter


class TaskListView(LoginRequiredMixin, FilterView):
    model = Task
    template_name = 'tasks/list.html'
    context_object_name = 'tasks'
    filterset_class = TaskFilter
    ordering = ['-created_at']

    def get_filterset_kwargs(self, filterset_class):
        kwargs = super().get_filterset_kwargs(filterset_class)
        kwargs['request'] = self.request
        return kwargs

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.request.GET.get('self_tasks') == 'on':
            return queryset.filter(author=self.request.user)

        return queryset


class TaskCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/form.html'
    success_url = reverse_lazy('tasks:list')
    success_message = _('Задача успешно создана')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Создать задачу')
        return context


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/detail.html'
    context_object_name = 'task'


class TaskUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/form.html'
    success_url = reverse_lazy('tasks:list')
    success_message = _('Задача успешно изменена')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Изменить задачу')
        return context


class TaskDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Task
    template_name = 'tasks/delete.html'
    success_url = reverse_lazy('tasks:list')
    success_message = _('Задача успешно удалена')
    error_message = _('Задачу может удалить только ее автор')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.error(
                request,
                _('Вы не авторизованы! Пожалуйста, войдите в систему.')
            )
            return redirect(reverse_lazy('login'))

        self.object = self.get_object()
        if self.object.author != request.user:
            messages.error(request, self.error_message)
            return redirect(self.success_url)

        return super().dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        response = super().delete(request, *args, **kwargs)
        messages.success(request, self.success_message)
        return response

task_manager/users/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.utils.translation import gettext as _
from .forms import UserForm, UserUpdateForm
from .models import Users
from task_manager.tasks.models import Task


class UserListView(ListView):
    model = Users
    template_name = 'users/list.html'
    context_object_name = 'users'


class UserCreateView(CreateView):
    model = Users
    form_class = UserForm  # Используем форму создания
    template_name = 'users/form.html'
    success_url = reverse_lazy('login')
    success_message = _('Пользователь успешно зарегистрирован!')

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, self.success_message)
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Регистрация')
        return context


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Users
    form_class = UserUpdateForm
    template_name = 'users/form.html'
    success_url = reverse_lazy('users:users')
    success_message = _('Пользователь успешно изменен!')

    def dispatch(self, request, *args, **kwargs):
        if request.user.pk != self.get_object().pk:
            messages.error(
                request,
                _('У вас нет прав для изменения другого пользователя.')
            )
            return redirect('users:users')
        return super().dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.get_object()
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Изменить пользователя')
        return context


class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = Users
    template_name = 'users/delete.html'
    success_url = reverse_lazy('users:users')
    success_message = _('Пользователь успешно удален!')
    error_message = _(
        'Невозможно удалить пользователя, потому что он связан с задачей'
    )

    def dispatch(self, request, *args, **kwargs):
        if request.user.pk != self.get_object().pk:
            messages.error(request, _(
                'У вас нет прав для изменения другого пользователя.')
            )
            return redirect('users:users')
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        user = self.get_object()
        if (Task.objects.filter(author=user).exists() or
            Task.objects.filter(executor=user).exists()):
            messages.error(request, self.error_message)
            return redirect(self.success_url)
        messages.success(request, self.success_message)
        return self.delete(request, *args, **kwargs)


class CustomLoginView(LoginView):
    template_name = 'users/login.html'

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, _('Вы залогинены'))
        return response

    def get_success_url(self):
        return reverse_lazy('home')


def custom_logout(request):
    logout(request)
    messages.success(request, _('Вы разлогинены'))
    return redirect('home')

task_manager/views.py
from django.views.generic import TemplateView
from django.views.defaults import page_not_found, server_error
import rollbar


class HomeView(TemplateView):
    template_name = "index.html"


def handler404(request, exception):
    return page_not_found(request, exception, template_name='404.html')


def handler500(request):
    return server_error(request, template_name='500.html')


def trigger_error(request):
    # Test error for Rollbar
    try:
        1 / 0
    except Exception as e:
        rollbar.report_exc_info()
        raise e

task_manager/templates/tasks/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <h1 class="my-4">{% trans "Удалить задачу" %}</h1>

    {% if not user.is_authenticated %}
    <div class="alert alert-danger" role="alert">
        {% trans "Вы не авторизованы! Пожалуйста, войдите в систему." %}
    </div>
    <a href="{% url 'login' %}" class="btn btn-primary">{% trans "Войти" %}</a>
    {% else %}
    <p>{% trans "Вы действительно хотите удалить задачу" %} <strong>{{ object.name }}</strong>?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">
            {% trans "Да, удалить" %}
        </button>
        <a href="{% url 'tasks:list' %}" class="btn btn-secondary">{% trans "Отмена" %}</a>
    </form>
    {% endif %}
</div>
{% endblock %}

task_manager/templates/tasks/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <h1 class="my-4">{% trans "Просмотр задачи" %}</h1>

    <div class="card">
        <div class="card-header bg-secondary text-white">
            <h2>{{ task.name }}</h2>
        </div>
        <div class="card-body">
            <p class="card-text">{{ task.description }}</p>
            <div class="container">
                <div class="row border-bottom p-2">
                    <div class="col fw-bold">{% trans "Автор" %}</div>
                    <div class="col">{{ task.author.get_full_name }}</div>
                </div>
                <div class="row border-bottom p-2">
                    <div class="col fw-bold">{% trans "Исполнитель" %}</div>
                    <div class="col">
                        {% if task.executor %}
                            {{ task.executor.get_full_name }}
                        {% else %}
                            {% trans "Не назначен" %}
                        {% endif %}
                    </div>
                </div>
                <div class="row border-bottom p-2">
                    <div class="col fw-bold">{% trans "Статус" %}</div>
                    <div class="col">{{ task.status.name }}</div>
                </div>
                <div class="row border-bottom p-2">
                    <div class="col fw-bold">{% trans "Дата создания" %}</div>
                    <div class="col">{{ task.created_at|date:"d.m.Y H:i" }}</div>
                </div>
                <div class="row border-bottom p-2">
                    <div class="col fw-bold">{% trans "Метка" %}</div>
                    <div class="col">
                        {% for label in task.labels.all %}
                            <span class="badge bg-secondary">{{ label.name }}</span>
                        {% empty %}
                            {% trans "Нет меток" %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <a href="{% url 'tasks:update' task.id %}" class="btn btn-primary">
                {% trans "Изменить" %}
            </a>
            <a href="{% url 'tasks:delete' task.id %}" class="btn btn-danger">
                {% trans "Удалить" %}
            </a>
        </div>
    </div>
</div>
{% endblock %}

task_manager/templates/tasks/form.html
{% extends "base.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
<div class="container">
    <h1 class="my-4">
        {% if object %}{% trans "Изменить задачу" %}{% else %}{% trans "Создать задачу" %}{% endif %}
    </h1>

    <form method="post">
        {% csrf_token %}

        {% bootstrap_field form.name show_label=True %}
        {% bootstrap_field form.description show_label=True %}
        {% bootstrap_field form.status show_label=True %}
        {% bootstrap_field form.executor show_label=True %}
        {% bootstrap_field form.labels show_label=True %}

        {% if object %}
            <div class="mb-3">
                <label class="form-label">{% trans "Автор" %}</label>
                <p>{{ object.author.get_full_name }}</p>
            </div>
        {% endif %}

        <button type="submit" class="btn btn-primary">
            {% if object %}
                {% trans "Изменить" %}
            {% else %}
                {% trans "Создать" %}
            {% endif %}
        </button>
    </form>
</div>
{% endblock %}

task_manager/templates/tasks/list.html
{% extends "base.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
<div class="container">
    <h1 class="my-4">{% trans "Задачи" %}</h1>

    <a href="{% url 'tasks:create' %}" class="btn btn-primary mb-3">
        {% trans "Создать задачу" %}
    </a>

    <form method="get" class="mb-4">
        {% bootstrap_field filter.form.status show_label=True %}
        {% bootstrap_field filter.form.executor show_label=True %}
        {% bootstrap_field filter.form.labels show_label=True %}

        <div class="form-group mb-3">
            <div class="form-check">
                <input type="checkbox"
                        name="self_tasks"
                        id="id_self_tasks"
                        class="form-check-input"
                        {% if request.GET.self_tasks %}checked{% endif %}>
                <label class="form-check-label" for="id_self_tasks">
                        {% trans "Только свои задачи" %}
                </label>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">{% trans "Показать" %}</button>
        <a href="{% url 'tasks:list' %}" class="btn btn-secondary">{% trans "Сбросить" %}</a>
    </form>


    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>{% trans "Имя" %}</th>
                <th>{% trans "Статус" %}</th>
                <th>{% trans "Автор" %}</th>  <!-- Убедитесь что есть столбец автора -->
                <th>{% trans "Исполнитель" %}</th>
                <th>{% trans "Дата создания" %}</th>
                <th>{% trans "Метка" %}</th>
                <th>{% trans "Действия" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr>
                <td>{{ task.id }}</td>
                <td><a href="{% url 'tasks:detail' task.id %}">{{ task.name }}</a></td>
                <td>{{ task.status.name }}</td>
                <!-- ФИКС: отображаем автора задачи -->
                <td>{{ task.author.get_full_name }}</td>
                <td>
                    {% if task.executor %}
                        {{ task.executor.get_full_name }}
                    {% endif %}
                </td>
                <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
                <td>
                    {% for label in task.labels.all %}
                        <span class="badge bg-secondary">{{ label.name }}</span>
                    {% empty %}
                        {% trans "Нет меток" %}
                    {% endfor %}
                </td>
                <td>
                    <a href="{% url 'tasks:update' task.id %}" class="btn btn-sm btn-primary">
                        {% trans "Изменить" %}
                    </a>
                    <a href="{% url 'tasks:delete' task.id %}" class="btn btn-sm btn-danger">
                        {% trans "Удалить" %}
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="8">{% trans "Нет задач" %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}